//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ID { get; set; }
        public int RatedUser { get; set; }
        public int RatedForUser { get; set; }
        public int RateValue { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
