//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ReportedUserID { get; set; }
        public string ReportText { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
